/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xingge_jnidemo_Add */

#ifndef _Included_com_example_xingge_jnidemo_Add
#define _Included_com_example_xingge_jnidemo_Add
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xingge_jnidemo_Add
 * Method:    addSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_xingge_jnidemo_Add_addSum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
